### ISSUE TITLE
yarn时一直卡在 Building fresh packages...  这一步

### ISSUE THREAD

**Issue by Asong2019** [netease-im/NIM_ReactNative_Demo#46]
yarn后一直卡住，尝试配置淘宝镜像、新建.yarnrc文件,修改全局.yarnrc文件，使用npm、cnpm等全都不行

yarn卡住信息如下：
warning " > react-native-fs@2.17.0" has unmet peer dependency "react-native-windows@^0.57.2".
warning "react-navigation > create-react-context@0.2.2" has unmet peer dependency "prop-types@^15.0.0".
[4/4] Building fresh packages...
[1/2] ⠈ react-native-elements                                                                                           [2/2] ⠈ realm    

卡很长很长时间后报错信息如下：
[4/4] Building fresh packages...
[1/2] ⡀ react-native-elements                                                                                           error D:\IMRN\NIM_ReactNative_Demo\node_modules\realm: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: D:\IMRN\NIM_ReactNative_Demo\node_modules\realm
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.16.1 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\IMRN\NIM_ReactNative_Demo\node_modules\realm\compiled\node-v72_win32_x64\realm.node" (not found)
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.29.2/realm-v2.29.2-node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://static.realm.io/node-pre-gyp/2.29.2/realm-v2.29.2-node-v72-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/2.29.2/realm-v2.29.2-node-v72-win32-x64.tar.gz
.
.
.省略
.
.
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\IMRN\\NIM_ReactNative_Demo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\IMRN\NIM_ReactNative_Demo\node_modules\realm
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\IMRN\NIM_ReactNative_Demo\node_modules\realm\compiled\node-v72_win32_x64\realm.node --module_name=realm --module_path=D:\IMRN\NIM_ReactNative_Demo\node_modules\realm\compiled\node-v72_win32_x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

**Comment by everlose** [comment]
realm 的安装总是充满了意外，推荐去看一看这一篇：https://cloud.tencent.com/developer/article/1607216
